model = "gpt-5.4"
model_reasoning_effort = "medium"
plan_mode_reasoning_effort = "high"

[tui]
status_line = [
    "model-with-reasoning",
    "current-dir",
    "git-branch",
    "context-remaining",
    "five-hour-limit",
    "weekly-limit",
    "fast-mode",
]

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"
env_http_headers = { CONTEXT7_API_KEY = "CONTEXT7_API_KEY" }

[mcp_servers.gh_grep]
url = "https://mcp.grep.app"

[mcp_servers.playwright]
command = "npx"
args = ["-y", "@playwright/mcp@latest"]

[mcp_servers.serena]
command = "uvx"
args = ["--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server"]

[mcp_servers.linear]
url = "https://mcp.linear.app/mcp"
