sort_order = ["tmux", "config", "zoxide"]

[default_session]
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "beril"
path = "~/Documents/Work/Collaborations/BERIL-research-observatory"

[[session]]
name = "co-scientist"
path = "~/Documents/Work/DataLakehouse/co-scientist"

[[session]]
name = "dl-etl"
path = "~/Documents/Work/DataLakehouse/Datalakehouse_ETL"

[[session]]
name = "healthfile"
path = "~/Documents/Personal/Startup/healthfile"

[[session]]
name = "mastitis"
path = "~/Documents/Personal/Startup/mastitis-detection"

[[session]]
name = "tp-annotation-pipeline"
path = "~/Documents/Work/tp-annotation-pipeline"

[[session]]
name = "tp-manuscript"
path = "~/Documents/Work/Manuscripts/trait-prediction-manuscript"

[[session]]
name = "tp-notes"
path = "~/Documents/Work/trait-prediction-notes"

[[session]]
name = "zendots"
path = "~/zendots"
