return {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    lazy = false,
    priority = 1000,
    config = function()
      require("catppuccin").setup({
        flavour = "mocha",
        transparent_background = false,
        term_colors = false,
        dim_inactive = {
          enabled = false,
          shade = "dark",
          percentage = 0.15,
        },
        background = {
          dark = "mocha",
          light = "latte",
        },
        styles = {
          keywords = { "italic" },
          types = { "bold" },
          conditionals = { "italic" },
          loops = { "italic" },
          comments = { "italic" },
          functions = { "bold" },
        },
        custom_highlights = function(colors)
          local darken = require("catppuccin.utils.colors").darken
          return {
            ["@variable.builtin"] = { italic = true },
            InclineNormal = { bg = colors.base },
            InclineNormalNC = { bg = colors.base },
            Pmenu = { bg = colors.base },
            Float = { bg = colors.base },
            FloatBorder = { bg = colors.base },
            NormalFloat = { bg = colors.base },
            FloatTitle = {
              fg = colors.crust,
              bg = colors.blue,
              bold = true,
              italic = true,
            },
            ZenBg = { bg = colors.base },
            TreesitterContext = { bg = colors.base, blend = 0 },
            TreesitterContextLineNumber = { bg = colors.mantle },
            TreesitterContextBottom = { style = {} },
            TreesitterContextLineNumberBottom = { style = {} },
            CmpItemKindCopilot = { fg = colors.teal },
            ["@comment.note"] = { link = "Comment" },
            ["@comment.todo"] = { link = "Comment" },
            ["@text.todo"] = { link = "Comment" },
            ["@comment.hint"] = { link = "Comment" },
            ["@comment.info"] = { link = "Comment" },
            ["@comment.error"] = { link = "Comment" },
            ["@comment.warning"] = { link = "Comment" },
            VimtexTodo = { bg = "NONE" },
            texCommentTodo = { link = "Comment" },
            Folded = { bg = colors.base },
            UfoFoldedFg = { fg = colors.teal, style = { "italic" } },
            MarkSignHL = { bg = colors.base, fg = colors.mauve },
            MarkSignNumHL = { bg = colors.base, fg = colors.mauve },
            MarkVirtTextHL = { bg = colors.base, fg = colors.mauve },
            CopilotSuggestion = {
              fg = darken(colors.teal, 0.5),
              italic = true,
            },
            IlluminatedWordText = { bg = colors.surface0, underline = true },
            IlluminatedWordRead = { bg = colors.surface0, underline = true },
            IlluminatedWordWrite = {
              bg = colors.surface0,
              underline = true,
              standout = true,
            },
            NoiceCmdlinePopup = { bg = colors.base, blend = 0 },
            NoicePopup = { bg = colors.base, blend = 0 },
            SnacksPickerTitle = {
              fg = colors.crust,
              bg = colors.mauve,
              bold = true,
              italic = true,
            },
            SnacksPickerListTitle = {
              fg = colors.crust,
              bg = colors.green,
              bold = true,
              italic = true,
            },
            SnacksPickerInputTitle = {
              fg = colors.crust,
              bg = colors.red,
              bold = true,
              italic = true,
            },
            SnacksPickerInputSearch = {
              fg = colors.crust,
              bg = colors.blue,
              bold = true,
              italic = true,
            },
            SnacksScratchKey = {
              fg = colors.crust,
              bg = colors.blue,
              bold = true,
              italic = true,
            },
            SnacksScratchDesc = {
              fg = colors.crust,
              bg = colors.blue,
              bold = true,
              italic = true,
            },
            GrappleTitle = {
              fg = colors.crust,
              bg = colors.blue,
              bold = true,
              italic = true,
            },
            GrappleFooter = { italic = true },
            MiniFilesTitle = {
              bg = colors.base,
              fg = colors.blue,
              bold = true,
              italic = true,
            },
            MiniFilesTitleFocused = {
              bg = colors.base,
              fg = colors.mauve,
              bold = true,
              italic = true,
            },
            SymbolUsageContent = { link = "Comment" },
            SymbolUsageRef = { link = "Function" },
            SymbolUsageDef = { link = "Type" },
            SymbolUsageImpl = { link = "@keyword" },
          }
        end,
        integrations = {
          blink_cmp = true,
          colorful_winsep = { enabled = true, color = "mauve" },
          copilot_vim = true,
          dap = true,
          dap_ui = true,
          diffview = true,
          flash = true,
          gitsigns = true,
          grug_far = true,
          indent_blankline = {
            enabled = true,
            scope_color = "mauve",
            colored_indent_levels = false,
          },
          illuminate = { enabled = true, lsp = true },
          lsp_saga = true,
          lsp_trouble = true,
          markdown = true,
          mini = { enabled = true, indentscope_color = "mauve" },
          native_lsp = { enabled = true, inlay_hints = { background = true } },
          neogit = true,
          neotest = true,
          noice = true,
          notify = true,
          nvim_surround = true,
          octo = true,
          overseer = true,
          rainbow_delimiters = true,
          render_markdown = true,
          semantic_tokens = true,
          snacks = { enabled = true },
          symbols_outline = true,
          telescope = { enabled = true },
          treesitter = true,
          treesitter_context = true,
          ufo = true,
          which_key = true,
        },
      })
    end,
  },
}
